language: java
jdk:
  - oraclejdk9

env:
  matrix:
    - COVERAGE=0.05 BUILD_TARGET=./monolithic/ui
    - COVERAGE=0.14 BUILD_TARGET=./monolithic/service/cart
    - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
    - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
    - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
    - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
    - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user
  global:
    - DOCKER_LOGIN=femionaks
    - secure: 25b63ed5-c9bf-407b-8b76-586e301ec741

install:
    "./gradlew clean jar"

script:
  - "./gradlew -p $BUILD_TARGET check"
  - "./gradlew jacocoTestReport"

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print "$3" "S4" "$5}'

before_deploy:
  - ./gradlew test jacocoTestCoverageVerification

deploy:
    provider: script
    script: echo 'WIP'
